services:
  - type: web
    name: zerodha-frontend
    env: static
    plan: free
    buildCommand: "npm run build"
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
